require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'NamalWoocommerce' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Additional pods


  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'RNRate', :path => '../node_modules/react-native-rate'
  pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'NamalWoocommerceTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    # Fix for Xcode 15+ and char_traits deprecation warnings
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        config.build_settings['WARNING_CFLAGS'] ||= ['$(inherited)', '-Wno-error=deprecated-declarations', '-Wno-deprecated-declarations']
      end
    end
  end
end


